export const FETCH_LEADERBOARD_REQUESTED = "FETCH_LEADERBOARD_REQUESTED";
export const FETCH_LEADERBOARD_SUCCEEDED = "FETCH_LEADERBOARD_SUCCEEDED";
export const FETCH_LEADERBOARD_FAILED = "FETCH_LEADERBOARD_FAILED";
export const TOGGLE_LEADERBOARD = "TOGGLE_LEADERBOARD";
